---
chdir: /home/wifigoadm/Chatforce
environment: production
address: 127.0.0.1
port: 3001
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
rackup: config.ru
max_conns: 1024
max_persistent_conns: 12
require: []
wait: 30
servers: 3
daemonize: true
